stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: technologieswithak2/max-live-spring-gateway
  DEPLOY_DIRECTORY: /opt/max-live/dev/max-live-deployment
  # Ensure SSH_PRIVATE_KEY is set in your GitLab CI/CD variables

build:
  stage: build
  tags:
    - max-live
  # image: docker:latest
  # services:
  #   - docker:dind
  script:
    - git config --global --add safe.directory $DEPLOY_DIRECTORY
    - pushd $DEPLOY_DIRECTORY
    - git checkout dev
    - git pull
    - VERSION=$(grep MAX_LIVE_SPRING_GATEWAY_VERSION .env | cut -d '=' -f2)
    - echo "VERSION=$VERSION"
    - NEW_VERSION=$(($VERSION + 1))
    - echo "NEW_VERSION=$NEW_VERSION"
    - IMAGE_NAME="$DOCKER_IMAGE_NAME:$NEW_VERSION"
    - echo "IMAGE_NAME=$IMAGE_NAME"
    - popd
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  tags:
    - max-live
  script:
    - git config --global --add safe.directory $DEPLOY_DIRECTORY
    - cd $DEPLOY_DIRECTORY 
    - git checkout dev
    - git pull
    - VERSION=$(grep MAX_LIVE_SPRING_GATEWAY_VERSION .env | cut -d '=' -f2)
    - NEW_VERSION=$(($VERSION + 1))
    - echo "MAX_LIVE_SPRING_GATEWAY_VERSION=$NEW_VERSION" > .env
    - cat .env
    - git add .env 
    - git commit -m "max-live-spring-gateway branch=dev $(date +\"%Y-%m-%d %H:%M:%S\")" 
    - git push






