spring.application.name=api-gateway
#spring.profiles.active=dev
spring.profiles.active=a-live-dev

# spring.cloud.config.fail-fast=false
# spring.cloud.config.label=latest
spring.cloud.config.enabled=false

#oauth2.resource.userInfoUri=/validateUser
oauth2.resource.userInfoUri=/realms/max-live/protocol/openid-connect/userinfo
webclient.server.timeout=60000

management.endpoints.web.exposure.include=health,info,env,metrics,gateway,refresh
management.endpoint.health.show-details=always
management.endpoint.gateway.enabled=true

server.ssl.enabled=false
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:server-keystore.jks
server.ssl.key-store-password=server@1234
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.2
server.ssl.client-auth=need
server.ssl.trust-store=classpath:server-keystore.jks
server.ssl.trust-store-password=server@1234



# Enable logging for Spring Cloud
#logging.level.org.springframework.cloud=DEBUG
## Enable logging for Spring Security
logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.security.oauth2=DEBUG
#logging.level.org.springframework.security.oauth2.client=DEBUG
logging.level.root=INFO

security.public-paths[0]=/business/api/v1/devices/status
security.public-paths[1]=/business/api/v1/devices
security.public-paths[2]=/business/api/v1/logged-in-user
security.public-paths[3]=/business/api/v1/complete-registration
security.public-paths[4]=/management/**
security.public-paths[5]=/actuator/**
security.public-paths[6]=/api/v1/storage/resource/upload

