server.port=8080
spring.data.mongodb.uri=mongodb://10.10.10.25:27017/max-live-db?authSource=admin
#spring.data.mongodb.uri=mongodb://103.209.43.28:27017/max-live-db?authSource=admin


oauth2.baseUrl=https://sso-dev.themaxlive.com


spring.cloud.gateway.routes[0].id=auth-server
spring.cloud.gateway.routes[0].uri=https://sso-dev.themaxlive.com
spring.cloud.gateway.routes[0].predicates[0] = Path=/oauth/**

spring.cloud.gateway.routes[1].id=max-live-spring-business
#spring.cloud.gateway.routes[1].uri=http://10.10.10.25:8095
spring.cloud.gateway.routes[1].uri=http://localhost:8095
spring.cloud.gateway.routes[1].predicates[0] = Path=/business/api/v1/**
spring.cloud.gateway.routes[1].filters[0].name=QueryParamFilter

spring.cloud.gateway.routes[2].id=max-live-spring-content-management-service
spring.cloud.gateway.routes[2].uri=http://10.10.10.25:8040
spring.cloud.gateway.routes[2].predicates[0] = Path=/api/v1/storage/**
spring.cloud.gateway.routes[2].filters[0].name=QueryParamFilter

spring.cloud.gateway.routes[3].id=max-live-spring-home
spring.cloud.gateway.routes[3].uri=http://10.10.10.25:8071
spring.cloud.gateway.routes[3].predicates[0] = Path=/api/v1/streaming/**
spring.cloud.gateway.routes[3].filters[0].name=QueryParamFilter

spring.cloud.gateway.routes[4].id=max-live-spring-teen-patti
spring.cloud.gateway.routes[4].uri=http://10.10.10.25:8083
spring.cloud.gateway.routes[4].predicates[0] = Path=/api/v1/gaming/**
spring.cloud.gateway.routes[4].filters[0].name=QueryParamFilter


spring.cloud.gateway.routes[5].id=exchange-token-route
spring.cloud.gateway.routes[5].uri=http://10.10.10.25:8020
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/auth-wrapper/**
