server.port=8080
spring.data.mongodb.uri=mongodb://internal-services.example.com:27017/a-live-db?authSource=admin
#spring.data.mongodb.uri=mongodb://mongo-public.example.com:27017/a-live-db?authSource=admin


oauth2.baseUrl=https://sso-dev.example.com


spring.cloud.gateway.routes[0].id=auth-server
spring.cloud.gateway.routes[0].uri=https://sso-dev.example.com
spring.cloud.gateway.routes[0].predicates[0] = Path=/oauth/**

spring.cloud.gateway.routes[1].id=live-platform-spring-business
spring.cloud.gateway.routes[1].uri=http://internal-services.example.com:8095
spring.cloud.gateway.routes[1].predicates[0] = Path=/business/api/v1/**
spring.cloud.gateway.routes[1].filters[0].name=QueryParamFilter

spring.cloud.gateway.routes[2].id=live-platform-spring-content-management-service
spring.cloud.gateway.routes[2].uri=http://internal-services.example.com:8040
spring.cloud.gateway.routes[2].predicates[0] = Path=/api/v1/storage/**
spring.cloud.gateway.routes[2].filters[0].name=QueryParamFilter

spring.cloud.gateway.routes[3].id=live-platform-spring-home
spring.cloud.gateway.routes[3].uri=http://internal-services.example.com:8071
spring.cloud.gateway.routes[3].predicates[0] = Path=/api/v1/streaming/**
spring.cloud.gateway.routes[3].filters[0].name=QueryParamFilter

spring.cloud.gateway.routes[4].id=live-platform-spring-teen-patti
spring.cloud.gateway.routes[4].uri=http://internal-services.example.com:8083
spring.cloud.gateway.routes[4].predicates[0] = Path=/api/v1/gaming/**
spring.cloud.gateway.routes[4].filters[0].name=QueryParamFilter


spring.cloud.gateway.routes[5].id=exchange-token-route
spring.cloud.gateway.routes[5].uri=http://internal-services.example.com:8020
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/auth-wrapper/**


