spring.data.mongodb.uri=mongodb://mongo-prod.example.com:27017/live-platform-db?authSource=admin
#spring.data.mongodb.uri=mongodb://mongo-prod-alt.example.com:27017/live-platform-db?authSource=admin

