server.port=8080

spring.r2dbc.url=r2dbc:postgresql://172.16.6.40:5432/mraims?schema=common
spring.r2dbc.username=mraims
spring.r2dbc.password=mraims

oauth2.baseUrl=https://sso-dev.themaxlive.com


spring.cloud.gateway.routes[0].id=auth-server
spring.cloud.gateway.routes[0].uri=https://sso-dev.themaxlive.com
spring.cloud.gateway.routes[0].predicates[0] = Path=/oauth/**

spring.cloud.gateway.routes[1].id=max-live-spring-business
spring.cloud.gateway.routes[1].uri=http://44.209.31.1:8095
spring.cloud.gateway.routes[1].predicates[0] = Path=/business/api/v1/**
spring.cloud.gateway.routes[1].filters[0].name=QueryParamFilter





# spring.zipkin.base-url=http://localhost:9411/
# spring.security.oauth2.client.provider.keycloak.issuer-uri=http://172.16.5.232:8080/auth/realms/CelloscopeIdentityManager
# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://172.16.5.232:8080/auth/realms/CelloscopeIdentityManager

