spring.application.name=api-gateway
spring.profiles.active=dev

# spring.cloud.config.fail-fast=false
# spring.cloud.config.label=latest
spring.cloud.config.enabled=false

#oauth2.resource.userInfoUri=/validateUser
oauth2.resource.userInfoUri=/realms/max-live/protocol/openid-connect/userinfo
webclient.server.timeout=60000

management.endpoints.web.exposure.include=health,info,env,metrics,gateway,refresh
management.endpoint.health.show-details=always
management.endpoint.gateway.enabled=true

server.ssl.enabled=false
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:server-keystore.jks
server.ssl.key-store-password=server@1234
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.2
server.ssl.client-auth=need
server.ssl.trust-store=classpath:server-keystore.jks
server.ssl.trust-store-password=server@1234



# Enable logging for Spring Cloud
logging.level.org.springframework.cloud=DEBUG

# Enable logging for Spring Security
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.oauth2.client=DEBUG
logging.level.root=TRACE
